org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
loom.ignoreDependencyLoomVersionValidation=true
# Common metadata
mod_license = MIT
mod_sources = https://github.com/Engine-Room/Flywheel
mod_issues = https://github.com/Engine-Room/Flywheel/issues
mod_homepage = https://github.com/Engine-Room/Flywheel
# Flywheel metadata
flywheel_id=flywheel
flywheel_name=Flywheel
flywheel_version=1.0.3
flywheel_description=An overhauled entity and block entity rendering API.
# Vanillin metadata
vanillin_id=vanillin
vanillin_name=Vanillin
vanillin_version=1.1.0
vanillin_description=Instanced rendering for entities and block entities via Flywheel.
# Vanillin dependencies
flywheel_maven_version_range=[1.0.0,2.0)
flywheel_semver_version_range=>=1.0.0 <2.0.0

# Mod dependency declarations
minecraft_semver_version_range = 1.21.7
minecraft_maven_version_range = [1.21.7]
fabric_api_version_range = >=0.129.0
neoforge_version_range = [21.7.13-beta,)

# General build dependency versions
java_version = 21
arch_loom_version = 1.10.430
parchment_minecraft_version = 1.21.6
parchment_version = 2025.06.29

# Minecraft build dependency versions
minecraft_version = 1.21.7
neoforge_version = 21.7.13-beta
fabric_loader_version = 0.16.14
fabric_api_version = 0.129.0+1.21.7

# Build dependency mod versions
sodium_version = mc1.21.6-0.6.13
iris_version = 1.9.1+1.21.7

# Publication info
flywheel_group=dev.engine-room.flywheel
vanillin_group=dev.engine-room.vanillin
artifact_minecraft_version = 1.21.7
